[package]
name = "bec-fw"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { version = "0.7", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = { version = "0.7" }
stm32f0 = { version = "0.15", features = ["stm32f0x1"] }
